name: CI CD

on:
  push:
    branches:
      - prod
jobs:
  build-android:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create .env.production file
        run: |
          echo "WEB_CLIENT_ID=${{ secrets.WEB_CLIENT_ID }}" > .env.production
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env.production
          echo "VERIFICATION_API=${{ secrets.VERIFICATION_API }}" >> .env.production
          echo "SEND_MAIL_API=${{ secrets.SEND_MAIL_API }}" >> .env.production
          echo "CREATE_DRIVER_API=${{ secrets.CREATE_DRIVER_API }}" >> .env.production

      - name: Install npm dependencies
        run: |
          npm install

      - name: Build Android Release
        run: |
          source .env.production
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: bus-on-time
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload Artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: android/app/build/outputs/apk/release/app-release.apk
